[package]
name = "rollgui2"
version = "0.1.0"
edition = "2021"

[profile.dev.package.'*']
opt-level = 3

[dependencies]
macroquad = "0.3"
egui = "0.16.1"
egui-macroquad = "0.8.0"
structopt = "0.3.21"
serde = {version="1.0.104", features = ["derive"]}
serde_derive = "1.0.104"
serde_json = "1.0.44"
quad-net = "0.1.1"
base64 = "0.13.0"
ureq = "2.4.0"