[package]
name = "rollgui2"
version = "0.1.0"
edition = "2021"

[profile.dev.package.'*']
opt-level = 3

[dependencies]
macroquad = "0.3"
egui = "0.15"
egui-macroquad = "0.7"
structopt = "0.3.21"
rust-ini = "0.17.0"
serde = {version="1.0.104", features = ["derive"]}
serde_derive = "1.0.104"
serde_json = "1.0.44"
# Note : dependencie added for wasm support, see https://docs.rs/getrandom/latest/getrandom/#webassembly-support
getrandom = { version = "0.2", features = ["js"] }
